backend:
  name: git-gateway
  repo: jwknz/gatsy-netlify-cms
  branch: main

media_folder: static/assets
public_folder: /assets

site_url: https://venerable-peony-dafab7.netlify.app

collections:
  - name: pages
    label: pages
    label_singular: "my_page"
    folder: "src/content/pages"
    create: true
    fields:
      - { name: title, label: Title }
      - { name: path, label: Path }
      - { label: "slug", name: "slug", widget: "string" }
      - { name: date, label: Date, widget: datetime }
      - { label: "Tags", name: "tags", widget: "list", default: ["guides"] }
      - { label: "Order", name: "number", widget: "number", default: 0 }
      - { name: body, label: Body, widget: markdown }

  - name: testing
    label: testing
    label_singular: "my_tests"
    folder: "src/content/testing"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    fields:
      - { name: title, label: Title }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "slug", name: "slug", widget: "string" }
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { label: "Tags", name: "tags", widget: "list", default: ["guides"] }
      - { label: "Order", name: "number", widget: "number", default: 0 }
      - { name: body, label: Body, widget: markdown }